name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: gulp lint:other
    - run: gulp make-art
    - run: npm test
    - run: gulp typedoc
    - run: gulp lint:art
