name: Node.js CI

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - run: npx gulp lint:other make-api-doc lint:art

  make-art-and-test:

    name: test (Node.js ${{ matrix.node-version }} on ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['12', '14', '16', '18']
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx gulp make-art
    - run: npm test
